### ISSUE TITLE
В базе отсутствуют несколько программ

### ISSUE THREAD

**Issue by Gae4ka725** [mrkaban/LicenseChecker#1]
В базе данных отсутствуют несколько программ. Прикрепляю отчет с рабочего компьютера
[1.zip](https://github.com/mrkaban/LicenseCheker/files/4439074/1.zip)

**Comment by mrkaban** [comment]
Спасибо за отчет, при следующем обновлении базы данных внесу неизвестные программ из Вашего отчета.

**Comment by mrkaban** [comment]
База данных обновлена и опубликована. Спасибо за то, что помогаете сделать программу лучше!
