### ISSUE TITLE
В базе отсутствуют несколько программ

### ISSUE THREAD

**Issue by sudmed** [mrkaban/LicenseChecker#2]
В базе данных отсутствуют несколько программ 
[2.zip](https://github.com/mrkaban/LicenseChecker/files/4463270/2.zip)

**Comment by mrkaban** [comment]
Спасибо большое за отчет! На выходных постараюсь обработать!

**Comment by mrkaban** [comment]
База данных обновлена и опубликована. Спасибо за то, что помогаете сделать программу лучше!
