### ISSUE TITLE
Следы активации винды

### ISSUE THREAD

**Issue by sudmed** [mrkaban/LicenseChecker#3]
> Также в подробностях можно изучить следы активации, там указываются следы активаторов. В редких случаях туда могут попасть хорошие системные файлы. 

Как отделить мух от котлет? Плохие это файлы или хорошие?
C:\Windows\winsxs\amd64_microsoft-windows-n..on-hkmsvc.resources_31bf3856ad364e35_6.1.7600.16385_ru-ru_f98fb9f956df4085\
C:\Windows\winsxs\amd64_microsoft-windows-n..ssprotection-hkmsvc_31bf3856ad364e35_6.1.7601.17514_none_70367407ace652fb\

![2020-04-10_23-25-58](https://user-images.githubusercontent.com/15969654/79020929-df449480-7b82-11ea-99f2-ef7d6b4df0c9.png)

**Comment by mrkaban** [comment]
Это ошибка, мне нужно будет продумать, как немного изменить алгоритм.

Если Вам интересно как она работает:
`def sled_activation(): 
    dir = 'C:\\Windows\\' #в папке Windows (надо будет переделать на путь из реестра, забыл)
    spisok=[]
    for root, dirs, files in os.walk(dir): #далее перебираем папки внутри
        for subdir in dirs: #и сравниваем с одним из шаблонов ниже
            pattern=r'Активатор|Activator|активатор|kms|AAct_Tools|ConsoleAct'
            search_exemple = re.search(pattern, subdir, re.M|re.I)
            if search_exemple:
                s1 = root+'\\'+subdir+'\\'
                if s1.find("\\\\", 0, len(s1)) >= 1: #Только отдельно, удаление кавычек
                     s1 = s1.replace("\\\\", '\\')
                spisok.append(s1)
    return spisok`

Эти файлы совпали с шаблоном kms, нужно будет подумать как это лучше сделать.

Спасибо за то, что написали об ошибке!

**Comment by mrkaban** [comment]
Иными словами, они хорошие

**Comment by mrkaban** [comment]
Проблема должна быть решена в версии 1.2, проверил в виртуальной машине. Версия 1.2 будет опубликована немного позднее, я обязательно напишу о её публикации. В данный момент, там осталось доработать некоторые моменты.

**Comment by mrkaban** [comment]
Версия 1.2 опубликована
