### ISSUE TITLE
Не удалось синхронизировать БД

### ISSUE THREAD

**Issue by sudmed** [mrkaban/LicenseChecker#4]
При попытке обновить БД программы через "?" -> "Обновить базу данных" возникает ошибка
![2020-04-13_10-25-51](https://user-images.githubusercontent.com/15969654/79101540-65263280-7d71-11ea-96ae-40e18cee85a0.png)

Установка по умолчанию, запускает пользователь с правами админа.

**Comment by sudmed** [comment]
При очередной попытке - обновилось.
![2020-04-13_10-26-08](https://user-images.githubusercontent.com/15969654/79101649-ae768200-7d71-11ea-8edb-4f55d2ab466f.png)

**Comment by mrkaban** [comment]
Да, Вы правы. Обновление Lpro.db и пользовательской базы, по сути, находится в одном try except, их стоит разнести, и возможно по умолчанию её отключить, включение сделать возможным через настройки.

А ничего не могло блокировать доступ на запись в папку с программой? Такая проблема только на одной рабочей станции?

PS: Спасибо Вам большое, что находите ошибки и помогаете сделать программу лучше!!!

**Comment by mrkaban** [comment]
Вынес блок синхронизации пользовательской базы в отдельную try except конструкцию, поэтому, если возникает ошибка в синхронизации пользовательской БД, основная база должно будет спокойно обновиться и сообщить об этом. Опять же, изменения внесены в версию 1.2, которая еще не закончена. 

Стоит еще подумать о настройках, но вносить туда кроме синхронизации пока ничего.

О публикации версии 1.2 сообщу.

**Comment by mrkaban** [comment]
В версии 1.2 будет окно настроек и там можно будет включить синхронизацию пользовательской базы, по умолчанию она будет выключена. 

Версия 1.2 почти закончена, осталось только закончить автошириной в зависимости от содержимого в ручном поиске и медиа поиске.

**Comment by mrkaban** [comment]
Версия 1.2 опубликована
