### ISSUE TITLE
Спасибо Вам за программу!

### ISSUE THREAD

**Issue by s-r-grass** [mrkaban/LicenseChecker#5]
Здравствуйте Алексей! Мы с Вами и так знакомы много лет, но хотел лишний раз поблагодарить за разработку и поддержку программы LicenseChecker, которая описана на сайте КонтинентСвободы.рф ([ссылка на описание](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D1%83%D1%82%D0%B8%D0%BB%D0%B8%D1%82%D1%8B/%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%B0/licensechecker-%D0%BB%D0%B5%D0%B3%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE%D1%81%D1%82%D1%8C-%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC.html)).

**Comment by mrkaban** [comment]
Спасибо за теплые слова!!!
